tests/test_pipeline_output.py

created to merge a commit lost while Github was down.

fixed PR review: removed copying dict with pipeline input

---

allensdk/ipfx/_schemas.py
allensdk/ipfx/aibs_data_set.py
allensdk/ipfx/bin/run_feature_extraction.py
allensdk/ipfx/bin/run_pipeline.py
allensdk/ipfx/bin/run_sweep_extraction.py
allensdk/ipfx/data_set_features.py
allensdk/ipfx/ephys_data_set.py
allensdk/ipfx/ephys_extractor.py
allensdk/ipfx/ephys_features.py
allensdk/ipfx/nwb_reader.py
allensdk/ipfx/plot_qc_figures.py
allensdk/ipfx/qc_features.py
allensdk/ipfx/qc_protocol.py
allensdk/ipfx/stim_features.py
allensdk/ipfx/stimulus_protocol_analysis.py
tests/test_ephys_data_set.py
tests/test_pipeline_output.py
tests/test_specimens.csv

Resolve issue #56 (as well as #50). Now the code checks whether the sweep is truncated and for the unctruncated (i.e., completed sweeps) uses only recorded portion of the sweep (i.e., cut off trailing zeros).

Clipped spikes

---

allensdk/ipfx/aibs_data_set.py
allensdk/ipfx/bin/generate_pipeline_input_patchseq.py
allensdk/ipfx/bin/run_feature_extraction.py
allensdk/ipfx/bin/run_pipeline.py
allensdk/ipfx/bin/run_qc.py
allensdk/ipfx/bin/run_sweep_extraction.py
allensdk/ipfx/data_set_features.py
allensdk/ipfx/qc_features.py
allensdk/ipfx/qc_protocol.py
allensdk/ipfx/stim_features.py
allensdk/ipfx/stimulus_protocol_analysis.py
tests/test_specimens.csv

Misc commit with updated tests resulting from testing a set of 40 specimens.

Stim align

---

ipfx/x_to_nwb/ABFConverter.py
ipfx/x_to_nwb/DatConverter.py
ipfx/x_to_nwb/Readme.md

Add sweep info

---

tests/test_x_nwb.py

X-NWB Tests: Fix python import error

---

ipfx/bin/nwb_to_pdf.py
ipfx/x_to_nwb/Readme.md

Structuring is done in sweeps with cycle_id. Each sweep gets its own
page, each nwb file its pdf.
Closes #85.

X-NWB: Add script to create a PDF from NWB files

---

ipfx/x_to_nwb/ABFConverter.py
ipfx/x_to_nwb/DatConverter.py
tests/test_x_nwb.py

Now the tests pass with pynwb from today (aka 44b0d2a2 (Add NWBFile.timestamps_reference_time field. (#709), 2018-11-07)).

Upgrade latest pynwb

---

ipfx/bin/pipeline_from_nwb_file.sh
ipfx/data_set_features.py
ipfx/stimulus_protocol_analysis.py
tests/test_pipeline_output.py
tests/test_specimens.csv
tests/test_stimulus_protocol_analysis.py

Fix selection of hero sweep
Add rheobase/hero sweep tests
Refactor regression test

Fix hero sweep selection

---

ipfx/bin/run_x_to_nwb_conversion.py
ipfx/x_to_nwb/ABFConverter.py
requirements.txt
tests/test_x_nwb.py
tests/test_x_nwb_helper.py

I've adapted the requirements.txt already for the new pyABF version which got just released.

Upgrade py abf

---

ipfx/aibs_data_set.py
ipfx/ephys_data_set.py
tests/helpers_for_tests.py
tests/test_ephys_data_set.py
tests/test_nwb_reader.py
tests/test_ontology.py

This restructures the EphysDataSet and AibsDataSet classes and adds tests for EphysDataSet. IOW this is the groundwork for the new EphysDataSet class which reads NWBv2 data.

Add ephys dataset tests

---

ipfx/bin/run_feature_extraction.py
ipfx/bin/run_sweep_extraction.py
ipfx/data_set_features.py
ipfx/data_set_utils.py
ipfx/hbg_dataset.py
ipfx/qc_features.py
ipfx/x_to_nwb/ABFConverter.py
tests/.gitignore
tests/test_hbg_dataset.py

Closes #107.
The new class is currently called `HBGDataSet`.

Add EphysDataset derived class

---

ipfx/x_to_nwb/DatConverter.py
ipfx/x_to_nwb/hr_nodes.py
requirements.txt

The clamp mode detection was incorrect and is now fixed.
In addition some TimeSeries properties are now more accurately read out.
Close #140.

Miscellaneous DAT fixes

---

ipfx/bin/pipeline_from_nwb_file.py
ipfx/bin/pipeline_from_specimen_id.py
ipfx/bin/run_feature_extraction.py
ipfx/bin/run_pipeline.py
ipfx/bin/run_qc.py
ipfx/bin/run_sweep_extraction.py
ipfx/data_set_features.py
ipfx/logging_utils.py
ipfx/nwb_reader.py
ipfx/qc_features.py
ipfx/qc_protocol.py
ipfx/spike_train_features.py
ipfx/stimulus_protocol_analysis.py
ipfx/subthresh_features.py

Resolve numpy warning (Resolves #142)
Beautify logging output

Clean up logging output

---

ipfx/bin/run_x_to_nwb_conversion.py
ipfx/x_to_nwb/ABFConverter.py
ipfx/x_to_nwb/DatConverter.py
ipfx/x_to_nwb/Readme.md
ipfx/x_to_nwb/conversion_utils.py

Make compression configurable

---

ipfx/bin/generate_fx_input.py
ipfx/bin/generate_qc_input.py
ipfx/bin/run_pipeline.py
ipfx/epochs.py
ipfx/qc_feature_evaluator.py
ipfx/qc_feature_extractor.py
ipfx/qc_features.py
ipfx/sweep.py
ipfx/sweep_props.py
tests/test_epochs.py

The main theme of this PR is to  check integrity of the sweep before computing QC features.
This allows for multiple checks. Currently checking for:
1. whether recording was truncated before completion of experimental epoch
2. whether stimulus is absent
Issues are saved into sweep tags which could be saved into lims.

Sweep integrity checks

---

ipfx/bin/mcc_get_settings.py
ipfx/bin/run_x_to_nwb_conversion.py
ipfx/x_to_nwb/ABFConverter.py
ipfx/x_to_nwb/DatConverter.py
ipfx/x_to_nwb/Readme.md
requirements.txt

Add folder watch mode for MCC getter script and support multiple JSON files for ABF folder conversion

---

ipfx/bin/plot_ephys_nwb.py
ipfx/ephys_data_set.py
ipfx/nwb_reader.py
tests/test_ephys_data_set.py

Plot nwb fixes

---

ipfx/aibs_data_set.py
ipfx/hbg_dataset.py
ipfx/nwb_reader.py
test_requirements.txt
tests/test_nwb_reader.py

Build sweep mapping

---

ipfx/bin/get_fx_output.py

Return a file with the paths of the json files with the extracted features

---

ipfx/aibs_data_set.py
ipfx/ephys_data_set.py
ipfx/hbg_dataset.py
ipfx/nwb_reader.py
ipfx/qc_feature_extractor.py
tests/test_nwb_reader.py
tests/test_pipeline_output.py

Enable saving recording date

---

ipfx/qc_features.py
tests/test_qc_features.py
tests/test_specimens.csv

Ignore Test pulse when measuring resistance

---

ipfx/epochs.py
ipfx/qc_feature_extractor.py
ipfx/sweep.py
tests/test_epochs.py

Fail sweeps with no test pulse

---

ipfx/_schemas.py

Allow None value for CellFeatures in schema

---

ipfx/bin/generate_se_input.py
ipfx/bin/make_stimulus_ontology.py
ipfx/bin/plot_ephys_nwb.py
ipfx/bin/run_feature_collection.py
ipfx/bin/run_feature_extraction.py
ipfx/bin/run_feature_vector_extraction.py
ipfx/bin/run_qc.py
ipfx/bin/run_sweep_extraction.py
ipfx/ephys_data_set.py
ipfx/stimulus.py
tests/test_aibs_data_set.py
tests/test_ephys_data_set.py
tests/test_ontology.py
tests/test_specimens.csv

Automate ontology

---

tests/conftest.py
tests/test_x_nwb.py

no longer use deprecated pytest.config

---

ipfx/bin/run_nwb1_to_nwb2_conversion.py
ipfx/hbg_dataset.py
ipfx/nwb_reader.py
ipfx/stimulus.py
ipfx/x_to_nwb/NWBConverter.py
tests/test_hbg_dataset.py
tests/test_nwb_reader.py
tests/test_ontology.py
tests/test_specimens.csv

Address #260 
Create NWBConverter class for converting nwb1 to nwb2.
Add functions into nwb_reader in order to extract necessary metadata for creating nwb2 file.
Add a test that runs pipeline on nwb2 file.
Add a basic conversion script.

nwb1-to-nwb2 conversion

---

tests/helpers_for_tests.py
tests/test_nwb1_nwb2_conversion.py
tests/test_specimens.csv

Basic round trip testing for writing and then reading time series: acquisition, stimulus

Roundtrip tests for nwb2 files

---

ipfx/bin/run_feature_extraction.py
ipfx/nwb_append.py
ipfx/nwb_reader.py
tests/test_append_nwb.py

Solves #164
Need a feedback for best way of implementing tests: I did both ways using classes and functions
I am getting some warnings when adding data to nwb2 which still needs to be resolved.

Embedding spikes into nwb file

---

ipfx/bin/run_synphys_feature_vector_extraction.py
ipfx/synphys.py

@gouwens here are some simple changes I needed to get code to start running.

update import to work with current synphys database; fix for dealing with strings; use commenting.

---

tests/test_x_nwb.py

This reverts commit c246ad6a379d3b0376c4d848117b41a84abad368.

Revert "Tests: Reenable X-NWB tests"

---

ipfx/dataset/create.py
ipfx/dataset/ephys_data_interface.py
ipfx/dataset/ephys_nwb_data.py
ipfx/dataset/mies_nwb_data.py
ipfx/stimulus.py
tests/dataset/test_ephys_data_set.py
tests/dataset/test_ephys_nwb_data.py
tests/dataset/test_mies_nwb_data.py
tests/test_hbg_dataset.py
tests/test_nwb_reader.py

Tests for EphysNWBData and MiesNWBData. Addressing #363

Test mies nwb data

---

.gitattributes
.readthedocs.yml
docs/conf.py
docs/gallery/analysis_examples/all_analysis.py
docs/gallery/analysis_examples/lsq_analysis.py
docs/gallery/analysis_examples/ramp_analysis.py
docs/gallery/analysis_examples/short_square_analysis.py
docs/gallery/data/nwb2_H17.03.008.11.03.05.nwb
docs/gallery/qc_examples/sweep_qc.py
docs/gallery/spikes_examples/detect_spikes_single_sweep.py
docs/gallery/spikes_examples/detect_spikes_single_sweep_window.py
docs/gallery/spikes_examples/estimate_params.py
docs/gallery/spikes_examples/spike_train_features.py
ipfx/dataset/ephys_data_set.py
ipfx/dataset/ephys_nwb_data.py
requirements_docs.txt
tests/dataset/test_ephys_data_set.py

stashes an NWB2 mies file in git lfs for documentation. Switches the docs to use this file.
from this pr:
https://ipfx--389.org.readthedocs.build/en/389/auto_examples/index.html
master (NWB1):
https://ipfx.readthedocs.io/en/latest/auto_examples/index.html

379/update gallery for 1.0.0

---

docs/pipeline.rst
pull_request_template.md

Addresses a bullet point "qc and analysis pipeline" for the issue #36

Update documentation for the pipeline

---

ipfx/bin/run_pipeline_from_nwb_file.py

support qc out dir in run_pipeline_from_nwb_file

---

README.md
docs/index.rst
docs/quick_start.rst
docs/tutorial.rst

Thank you for contributing to the IPFX, your work and time will help to
advance open science! 
Give a brief overview of the issue you are solving. Succinctly
explain the GitHub issue you are addressing and the underlying problem
of the ticket. The commit header and body should also include this
message, for good commit messages see the [contribution guidelines](CONTRIBUTING.md).
Add a link to the issue on Github board
example: 
Addresses issue [#1234](git_hub_ticket_url)
Outline your solution to the previously described issue and
underlying cause. This section should include a brief description of
your proposed solution and how it addresses the cause of the ticket
Include a bulleted list or check box list of the implemented changes
in brief, as well …

update readme as to move quickstart to the documentation

---

docs/gallery/analysis_examples/all_analysis.py
docs/tutorial.rst
ipfx/bin/run_feature_extraction.py
ipfx/bin/run_pipeline.py
ipfx/data_set_features.py
ipfx/feature_record.py
ipfx/plot_qc_figures.py

Allows feature extractor to handle and record feature extraction failures.
Addresses issue #428 
Update cell features to return None instead of failing, add errors to cell_state.
[Allen Institute Contribution Guidelines](CONTRIBUTING.md)
[Numpy Standards](https://numpydoc.readthedocs.io/en/latest/format.html)
appropriate
Use this section to add anything you think worth mentioning to the
reader of the issue

428 Implements graceful degradation for feature extractor 

---

requirements.txt

Resolves: #488 
**Changes:**
Fix h5py version to recover functionality

Fix h5py package version

---

ipfx/bin/run_feature_extraction.py
ipfx/qc_feature_extractor.py
tests/data/specimens/Ctgf-T2A-dgCre;Ai14-495723.05.02.01/pipeline_output.json
tests/data/specimens/Pvalb-IRES-Cre;Ai14(IVSCC)-165172.05.02/pipeline_output.json
tests/data/specimens/Vip-IRES-Cre;Ai14-331294.04.01.01/pipeline_output.json

Resolves #470
Add features_state to the output and update tests

GH-470 Add features state to the json output

---

.circleci/config.yml

testing git-lfs
