setup.cfg

was trying to figure out why the tests weren't generating test reports -- this was it.

adding test report generation by default

---

requirements.txt

Since version 2.0.19 pyabf is being rewritten. In order to keep our
ABF -> NWB conversion working we stick to the old API.
Porting to the new API is planned once it is finalized.

Requirements.txt: Tighten version check on pyabf

---

allensdk/ipfx/x_to_nwb/ABFConverter.py

Since c27448d2 (add stimulus_description (#598), 2018-08-28) this can be
set in pynwb.

ABFConverter._createAcquiredSeries: Supply stimulus_description as well

---

requirements.txt

Since 9/15/2018 we have a new pynwb release which works for us.

requirements.txt: Use minimum version for pynwb

---

ipfx/x_to_nwb/ABFConverter.py
ipfx/x_to_nwb/DatConverter.py

This pynwb version finally accepts only datetime objects for
session_start_time and file_create_date.
Requires a unreleased pynwb version from master.
See also https://github.com/NeurodataWithoutBorders/pynwb/commit/8d6bd2eed3a402ae3d71ef3ce985634a0d592e74.

X-NWB: Upgrade to latest pynwb version

---

ipfx/bin/run_x_to_nwb_conversion.py
test_requirements.txt
tests/conftest.py
tests/test_x_nwb.py
tests/test_x_nwb_helper.py

Run the tests with
```
py.test.exe --numprocesses auto --do-x-nwb-tests test_x_nwb.py
```
Takes here around 3 minutes.
The files are downloaded on-demand only as I've added some caching scheme.
Closes #83, #84.

Add regression tests for X-NWB converters

---

ipfx/bin/nwb_to_pdf.py
ipfx/x_to_nwb/ABFConverter.py
ipfx/x_to_nwb/DatConverter.py
ipfx/x_to_nwb/utils.py
tests/test_x_nwb.py

For that we reuse the cycle_id logic but we now generate a integer
instead of a string.
Example file: www.byte-physics.de/Downloads/H18.28.015.11.12.nwb.
Closes #102.

X-NWB/DATConverter/ABFConverter: Add sweep numbers

---

requirements.txt

We already require that since 13487580 (X-NWB/DATConverter/ABFConverter:
Add sweep numbers, 2018-11-08).
Closes #86.

requirements.txt: Require latest pynwb version

---

requirements.txt

Only this version has the fix 6683635 (add list comprehension for
reading references in an array after file <80> (#740), 2018-11-19)
which is required for the SweepTable feature to be usable. This is used
in NwbXReader and now the tests pass.
Closes #123.

requirements.txt: Raise required pynwb version to 0.6.2

---

ipfx/nwb_reader.py

This is the PR for checking that the real and the assumed sweep number are the same.
The tests pass but I guess you have tons of data more ;)
The check is done in get_sweep_data for both MIES and pipeline NWB files.

Bail out on wrong sweep number

---

ipfx/bin/run_pipeline.py
ipfx/plot_qc_figures.py
ipfx/qc_features.py
ipfx/stim_features.py
tests/test_stim_features.py

Avoid using experiment epoch start index to determine stimuli properties because it takes negative values for the stimuli starting less than 500 ms after test pulse. 
Stop using experiment epoch start index for the plotting, rather use a hard coded value.
Improve get_stim_characterists function

Fix issues arising from stimulus starting less than 500 ms after test pulse

---

ipfx/bin/nwb_to_pdf.py
ipfx/x_to_nwb/ABFConverter.py
ipfx/x_to_nwb/DatConverter.py
ipfx/x_to_nwb/hr_bundle.py

For some ABF files the length of the stimset differs from the acquired
channels. This creates a wrong axis scaling as the plotting uses
constant size of the graphs.
Restrict the range to the minimum length to avoid that issue.

X-NWB/nwb_to_pdf.py: Limit plotting range to the minimum number of points

---

ipfx/epochs.py
ipfx/nwb_reader.py
ipfx/qc_features.py
ipfx/stim_features.py
tests/test_epochs.py
tests/test_stim_features.py

Eliminate redundant find_stim_start function and use consistently a single function for finding stim indexes.
Split epochs detection into a separate module

Fix bugs in stim start

---

ipfx/nwb_reader.py
tests/fetch_file.py
tests/test_hbg_dataset.py
tests/test_nwb_reader.py

In 44ea93e7 (NwbReader: Check that the assumed and the real sweep number
are the same, 2018-12-06) we added code to check that the assumed sweep
number is the same as the real sweep number.
But we can be better than that and just return the real sweep number if
requested.
Close #111.

NwbReader.get_sweep_number: Return the real sweep number

---

ipfx/ephys_data_set.py
ipfx/epochs.py
ipfx/plot_qc_figures.py
ipfx/qc_features.py
tests/test_epochs.py

Now experimental epoch is defined as: 
start index: 0.5 second before stimulus start index
end index:  0.5 second after stimulus end index
Thus, experimental epoch is an expected interval of the response.
The new definition simplifies checking for the sweep truncation: 
if the last index of the response is less than the end of the experimental epoch, then experiment is not fully recorded (i.e, truncated).

Redefine the meaning of experimental epoch

---

ipfx/aibs_data_set.py
ipfx/data_set_features.py
ipfx/ephys_data_set.py
ipfx/plot_qc_figures.py
ipfx/qc_protocol.py
ipfx/stimulus.py
ipfx/sweep.py
tests/test_sweep.py

Previously, selecting epochs of a sweep required re-loading data from the nwb file.
Now, sweep is created with all data and epochs are detected. We can now request different epochs on the existing sweep without needing to reload data. 
Epochs are now actions of the Sweep class rather than entire data set.
This PR is a bit of WIP...

Enabling selection of epochs on the existing sweep

---

ipfx/data_set_features.py
ipfx/ephys_data_set.py
ipfx/plot_qc_figures.py
ipfx/qc_feature_extractor.py
ipfx/qc_features.py
tests/test_ephys_data_set.py
tests/test_hbg_dataset.py

Some cells have duplicated test sweeps but marked as VoltageClamp
This feature enable choosing only the desired clamp modes.
Resolves #181

Enable checking for clamp mode when returning sweep number

---

ipfx/aibs_data_set.py
ipfx/bin/run_feature_extraction.py
ipfx/data_set_features.py
ipfx/ephys_data_set.py
ipfx/hbg_dataset.py
ipfx/plot_qc_figures.py
ipfx/sweep_props.py
tests/test_aibs_data_set.py
tests/test_ephys_data_set.py
tests/test_hbg_dataset.py

At the stage of the feature extraction, the `sweep_record` is missing `clamp_mode` information.
Thus, adding a method for determining the clamp mode. Call it before building a sweep_table.
I had to refactor AibsDataSet and HBGDataSet to factor out individual functions for determining sweep properties.
Resolves #203, #205

Extract clamp mode from nwb file

---

ipfx/bin/run_feature_vector_extraction.py
ipfx/data_set_features.py
ipfx/feature_extractor.py
ipfx/spike_detector.py
ipfx/spike_train_features.py
ipfx/stimulus_protocol_analysis.py

Gives more flexibility to filter out certain spikes during feature extraction, including:
- ability to reject spikes detected with start at the start of the stimulus interval (can occur with strong short square stimuli, for example)
- can exclude clipped spikes from basic sweep feature calculations (incorrect spike detection can occur when sweep is terminated early)
- uses these new features in `run_feature_vector_extraction` script

More qc-related spike filtering options

---

ipfx/defaults/stimulus_ontology.json

Fixes noise stimuli wrongly marked as short squares

fix wrong name for certain noise stimuli

---

ipfx/aibs_data_set.py
ipfx/ephys_data_set.py
ipfx/nwb_reader.py
tests/test_aibs_data_set.py
tests/test_specimens.csv

Both data and unit names must be in base SI units. 
For example, we should have data in Volts (not mV)

Get data from nwb in base SI units

---

ipfx/bin/run_nwb1_to_nwb2_conversion.py
ipfx/nwb_reader.py
tests/conftest.py
tests/helpers_for_tests.py
tests/test_nwb1_nwb2_conversion.py
tests/test_x_nwb.py

Perform nwb schema validation.
Problem:
pynwb.validate() perform validation but does not catch all exceptions and may error out for corrupt files.
Solution: 
test function to catch and return all exception.
When pynwb does not catch all exception

Adding validation test for converted nwb1>nwb2 files

---

ipfx/bin/run_nwb1_to_nwb2_conversion.py
ipfx/x_to_nwb/NWBConverter.py
requirements.txt
tests/test_nwb1_nwb2_conversion.py

pynwb started using object_id for objects that changes every time file gets created even from the same data. Thus, using h5diff returns a difference when performing regression testing.
Per suggestion from pynwb developer, I added an option to monkey patched object_id property to produce a fixed value for all object ids. This will be used for regression testing.
By default this option will be disabled and allow generating genuine object_ids when converting files.

Nwb2 regression test

---

requirements.txt

nwb related tests were failing after hdmf was upgraded to ver 1.2. Freezing now hdmf to 1.1.2

freeze hdmf version to 1.1.2

---

pytest.ini

hide hdmf's warning 'add child is depcreated' when adding
device and electrode to the nwbfile
Resolve 276

Hide deprecation warning from pynwb

---

ipfx/x_to_nwb/ABFConverter.py
requirements.txt
tests/test_x_nwb.py

So this now makes the ABF conversion work on Linux as well. While doing that I also found a bug with the starting_time.
I also reenabled the X-NWB tests as they are the only way to find these kind of errors.
Requires a yet-to-be-released pyABF version, see https://github.com/swharden/pyABF/pull/97 for the PR.
While doing that I also fixed https://github.com/swharden/pyABF/pull/94 but that is unrelated to our use.
Close #282.

Make abf conversion work on linux

---

requirements.txt

install from pyabf that does not import numpy to setup

---

ipfx/lims_queries.py

The processing pipeline no longer automatically produces files named "<specimen_id>.nwb", which are recorded in LIMS with a well-known file type name "NWB". However, LIMS still is recording an entry for those non-existent files, which causes errors downstream.
Therefore, I switched the LIMS query to prefer the "NWBIgor"-type file if that entry exists, and only return an "NWB"-type file if there is no entry for the former.

Switch to getting NWBIgor files from LIMS

---

requirements.txt

installing from my fork should no longer be necessary

stop installing pyabf from a fork (changes in mainline)

---

ipfx/script_utils.py

We need to set the recording epoch in the `validate_sweeps()` or else it doesn't properly exclude truncated sweeps.

Fix validation of sweeps by using recording epoch

---

ipfx/nwb_reader.py

The `nwb_reader` object ends up making many independent `h5py.File()` calls that add up to a lot of extra processing time. This PR changes the initializer to load the whole file into memory by default, and then uses that in the other methods rather than hitting the file system each time.
By my profiling, the savings are pretty substantial. For a test cell, the time it took to create an `AibsDataSet` object went from ~7 seconds to 1.5 seconds. And it reduced the time the test suite took by at least 30 seconds.

Load h5 file into memory by default

---

tests/test_feature_vector.py

Some of the tests for the feature vector code are written as integration tests when they ought to be unit tests - they load up data from an nwb file and then call multiple functions in sequence. Much of this data is irrelevant to the functions being called, and the dependence on an nwb file makes these tests hard to run outside the institute (and hard to update for the move to nwb2). This pr replaces these tests with focused unit tests.

unit tests for feature vector

---

README.md
ipfx/aibs_data_set.py
ipfx/data_set_utils.py
ipfx/ephys_data_set.py
ipfx/hbg_dataset.py
ipfx/nwb_reader.py
ipfx/x_to_nwb/NWBConverter.py
tests/test_ephys_data_set.py
tests/test_nwb1_nwb2_conversion.py

adds warnings and a readme message warning that we are dropping python2 and nwb1 support.
Also makes the nwbreader compatible with "amperes" and "volts" as units.
A note: There are a bunch of dataset tests that just assert notimplemented errors are raised. I moved a method to ephysdataset, which broke some, so I deleted them. I did this because:
1. they don't really test anything
2. we are replacing these tests anyways
If you disagree with this approach, lemme know. Another way would be to add more errors to the pytest raises statements.

add deprecation warnings in preparation for 1.0.0

---

ipfx/attach_metadata/sink/nwb2_sink.py
tests/attach_metadata/test_nwb2_sink.py

manually set "modified" on nwb containers in attach_metadata

---

ipfx/attach_metadata/sink/nwb2_sink.py
ipfx/bin/nwb_to_pdf.py
ipfx/dataset/ephys_nwb_data.py
ipfx/nwb_append.py
requirements.txt
setup.py
tests/attach_metadata/test_cli.py
tests/attach_metadata/test_nwb2_sink.py
tests/data/nwb/Ctgf-T2A-dgCre;Ai14-495723.05.02.01-compressed-V2.nwb
tests/data/nwb/Ctgf-T2A-dgCre;Ai14-495723.05.02.01.nwb
tests/data/nwb/Pvalb-IRES-Cre;Ai14(IVSCC)-165172.05.02-compressed-V2.nwb
tests/data/nwb/Pvalb-IRES-Cre;Ai14(IVSCC)-165172.05.02.nwb
tests/data/nwb/Vip-IRES-Cre;Ai14-331294.04.01.01-compressed-V2.nwb
tests/data/nwb/Vip-IRES-Cre;Ai14-331294.04.01.01.nwb
tests/data/specimens/Ctgf-T2A-dgCre;Ai14-495723.05.02.01/pipeline_input.json
tests/data/specimens/Pvalb-IRES-Cre;Ai14(IVSCC)-165172.05.02/pipeline_input.json
tests/data/specimens/Vip-IRES-Cre;Ai14-331294.04.01.01/pipeline_input.json
tests/helpers_for_tests.py
tests/test_append_nwb.py
tests/test_mies_nwb_pipeline_output.py

Load namespaces from NWB files when provided. Makes various supporting changes, such as updating tests & their data. This handles cutting-edge MIES NWBs
In order to be fully done with this PR, we need:
- new releases of pynwb and hdmf
- to remove the patch in requirements.txt pointing at in-development branches of those packages.
In the meantime, you can use these changes by installing the requirements via `pip insatll -r requirements.txt`. I have prepared a conda environment at /allen/aibs/informatics/nileg/ipfx_june/test_env/ with this branch installed.

#408 update ipfx nwb reading to handle in-file namespaces. Update tests

---

docs/conf.py
requirements_docs.txt

adds numpydoc to sphinx extensions, allowing the "Parameters" section to render.

fix apidoc section rendering

---

ipfx/dataset/ephys_nwb_data.py

Suppress "ignoring namespace '%s' because it already exists" errors when loading an ephys dataset from an NWB file
Addresses issue [#425](https://github.com/AllenInstitute/ipfx/issues/425)
Alias NWBHDF5IO class with a context manger that suppresses the undesired warning

suppresses ignoring namespace errors in NWBHDF5IO

---

docs/gallery/analysis_examples/ramp_analysis.py
ipfx/data_set_features.py
ipfx/sweep_props.py

Change to import EphysDatSet from the dataset.ephys_data_set
to avoid the deprecation warning
Thank you for contributing to the IPFX, your work and time will help to
advance open science! 
Address #426 
import from the dataset.ephys_data_set

GH-426 Fix deprecation warning for ephys_data_set

---

.circleci/config.yml
.readthedocs.yml
setup.py

The package is tested against python 3.6, so I guess we should stick to 3.6

use python 3.6 throughout: test, deploy, docs

---

ipfx/_schemas.py
ipfx/bin/run_feature_extraction.py
ipfx/bin/run_pipeline.py
ipfx/bin/run_pipeline_from_nwb_file.py
ipfx/bin/run_sweep_extraction.py
ipfx/nwb_append.py

Add an optional write_spikes with the default in the run_feature_extractor set to True
but in the run_from_nwb_file the default is set to False
this would avoid making changes to LIMS. Users processing dandi files would by default have write_spikes=False.
Addresses issue [#444]
Do not add spikes processing module if it already exists

Gh 444/use spikes if already exist

---

docs/quick_start.rst
ipfx/bin/generate_pipeline_input.py
ipfx/bin/run_pipeline.py
ipfx/bin/run_pipeline_from_nwb_file.py

- run_pipeline_from_nwb_file's qc_fig_dir argument is now relative to cell_dir (can still specify an absolute path if you like)
- can argue --qc_fig_dir with build figures and store them in "qc_figs"
- adds documentation for run_pipeline_from_nwb_file's parameters
I had to choose between consistency with other executables and consistency with the other parameters of this executable. I went with the latter, but I'm not particularly wedded to the choice. Let me know in your review what you think

GH-454 run_pipeline_from_nwb_file is relative to cell output directory

---

docker/py36/Dockerfile
requirements.txt

Addresses #471
Notes: 
1. I hosted in on the Docker Hub since I am not sure how to get the image on the aibs-artifactory.corp.alleninstitute.org. When Nick is back we can ask him how to upload the image to the artifactory.
2. This PR is against mastersince this is a hotfix. May be not so hot, but a fix anyway :)
Validation: 
the github branch CI on bamboo is passing!

GH-471 Update pynwb requirements

---

ipfx/plot_qc_figures.py
requirements.txt

**Background:**
Sometimes AP feature value may be null. Previously these were treated as np.nan but at some point we changed np.nan to None that broke plotting.
This bug was discovered when validating http://jira.corp.alleninstitute.org/browse/PBS-2458 as a solution to #469 
The slow trough feature for the rheobase sweep is null for the nwb file in #469.
**Solution:**
allow None values into the plot which would silently omit the value from the plot as it did before the breaking change 
**Validation:**
should generating figures without errors:
`python -m ipfx.bin.run_pipeline_from_nwb_file /path/to/nwb2_H19.06.351.11.16.01.01.nwb /output/dir/ --qc_fig_dir
`

Prevent mismatch between number of values and labels in AP feature plots 

---

ipfx/x_to_nwb/hr_segments.py

Addresses #473 
In the DAT converter, segments of sweeps are constructed with length calculated by floating point division. The result can be slightly less or greater than the the actual integer value, so applying math.trunc was dropping data points in some cases. This fixes the issue by rounding instead, and raises an error if the unrounded value is not close to an integer.

fix segment length rounding error #473 

---

ipfx/qc_feature_extractor.py
ipfx/stim_features.py

Bugfix, address #498 
Runs were failing because nan stimulus amplitudes converted to null when written to json, and LIMS EphysStimulus requires a numeric amplitude.

returns 0.0 for amplitude instead of nan

---

.circleci/config.yml

Bugfix - circleci deploy_pypi job is failing due to no rust compiler found. Rust is needed to build cryptography from source, but updating pip and cryptography should grab a wheel instead, so no need for Rust.

upgrades pip so cryptography wheel gets installed

---

CHANGELOG.md
ipfx/bin/run_feature_vector_extraction.py
ipfx/feature_vectors.py
tests/data/feature_vector/fv_inst_freq_TEMP.npy
tests/data/feature_vector/fv_psth_TEMP.npy
tests/data/feature_vector/fv_spiking_fast_trough_v_TEMP.npy
tests/data/feature_vector/fv_spiking_peak_v_TEMP.npy
tests/data/feature_vector/fv_spiking_threshold_v_TEMP.npy
tests/data/feature_vector/fv_spiking_upstroke_downstroke_ratio_TEMP.npy
tests/data/feature_vector/fv_spiking_width_TEMP.npy
tests/test_feature_vector.py

Thank you for contributing to the IPFX, your work and time will help to
advance open science! 
Give a brief overview of the issue you are solving. Succinctly
explain the GitHub issue you are addressing and the underlying problem
of the ticket. The commit header and body should also include this
message, for good commit messages see the [contribution guidelines](CONTRIBUTING.md).
The feature vector extraction code sometimes produces vectors of different lengths that cannot be saved as an array in an H5 file. This happens because of differences in the floating point approximations of start and end times in different cells.
Add a link to the issue on Github board
Addresses issue #521 
Outline your solution to the previously described issue and …

Fix duration rounding to address #521

---

ipfx/bin/plot_ephys_nwb.py
ipfx/data_set_features.py
ipfx/dataset/ephys_data_set.py
ipfx/script_utils.py
ipfx/sweep.py
tests/test_chirp.py
tests/test_feature_vector.py
tests/test_sweep.py

One of two options to address issue #508 by selecting the recording epoch by default as sweeps are created.
The recording epoch already properly detects the valid portion of sweeps, but isn't always used in the early stages of QC or when detecting the stim epoch. By making sure it's always used, the full sweep info from the NWB is retained, but all code runs properly by dealing with the valid portion only.
- selects recording rather than sweep epoch by default, and removes redundant calls to select recording epoch
- restructures epoch detection to use recording epoch for stim epoch detection also
- restores previous behavior for missing data represented as zeros, replacing with nan rather than truncating
- fixes tests for compatibility with changes
- …

Address nan issue by selecting recording epoch as default

---

ipfx/epochs.py

Addresses #525 by adjusting get_stimulus_epoch to require a complete stimulus (both onset and offset) to define the stimulus epoch. 
Along with the already merged fixes, this should supersede #511 I believe.

require stim offset to define epoch

---

CHANGELOG.md
RELEASE_INSTRUCTIONS.md

2.0.0 release

---

TESTING.md
requirements.txt
tests/data/Vip-IRES-Cre;Ai14(IVSCC)-226110.03.01_ITC18USB_Dev_0-nwb-schema-2.9.0.nwb
tests/data/Vip-IRES-Cre;Ai14(IVSCC)-236654.04.02_ITC18USB_Dev_0-nwb-schema-2.9.0.nwb
tests/test_run_feature_vector.py

Require pinned pynwb version again

---

ipfx/bin/make_stimulus_ontology.py
ipfx/dataset/ephys_nwb_data.py
ipfx/nwb_append.py
ipfx/time_series_utils.py
pytest.ini
requirements.txt
tests/attach_metadata/test_cli.py
tests/attach_metadata/test_nwb2_sink.py
tests/dataset/test_ephys_nwb_data.py
tests/dataset/test_hbg_nwb_data.py
tests/dataset/test_mies_nwb_data.py
tests/test_append_nwb.py
tests/test_ephys_extractor.py
tests/test_mies_nwb_pipeline_output.py

Fix and silence warnings
